{
  "hash": "4252a3e6085bcd9656f4c0310a1a49c3",
  "result": {
    "markdown": "\n\n::: {.cell}\n\n```{.r .cell-code}\nload(file='metadag_work_space.RData')\n```\n:::\n\n\n\n# Metabolic Graphs\n\nWe present here some analysis examples of the metabolic graphs generated in GraphML format.\n\n## Metabolic graphs for each organism\n\nRead the individual metabolic graphs generated for Homo sapiens (KEGG id: hsa) in the directory(Individuals/hsa)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexperiment=\n  \"result_0a845f74-826e-3b46-aed9-e7ecf74db262/\"\npath_exp=paste0(\"data/\",experiment)\nfiles_hsa=dir(paste0(path_exp,\"Individuals/hsa\"))\nfiles_hsa\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"hsa_mDAG.graphml\"       \"hsa_mDAG.pdf\"           \"hsa_mDAG.svg\"          \n [4] \"hsa_mDAG_adj.csv\"       \"hsa_mDAG_biggerDAG.pdf\" \"hsa_mDAG_biggerDAG.svg\"\n [7] \"hsa_mDAG_nl.csv\"        \"hsa_mDAG_structure.csv\" \"hsa_R_adj.csv\"         \n[10] \"hsa_R_nl.csv\"           \"hsa_RC.graphml\"         \"hsa_RC.pdf\"            \n[13] \"hsa_RC.svg\"             \"hsa_summary.txt\"       \n```\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\\begin{tabular}{l|l}\n\\hline\nfiles\\_Individual\\_hsa & Description\\\\\n\\hline\nhsa\\_mDAG.graphml & m-DAG GraphML format\\\\\n\\hline\nhsa\\_mDAG.pdf & m-DAG pdf graphic\\\\\n\\hline\nhsa\\_mDAG.svg & m-DAG svg graphic\\\\\n\\hline\nhsa\\_mDAG\\_adj.csv & csv file with the adjacency matrix of the m-DAG\\\\\n\\hline\nhsa\\_mDAG\\_biggerDAG.pdf & pdf graphic with the biggest conected componet of the m-DAG\\\\\n\\hline\nhsa\\_mDAG\\_biggerDAG.svg & svg graphic with the biggest conected componet of the m-DAG\\\\\n\\hline\nhsa\\_mDAG\\_nl.csv & csv file with the node (MBBs) labels  of the m-DAG\\\\\n\\hline\nhsa\\_mDAG\\_structure.csv & csv file with all connected components of the m-DAG\\\\\n\\hline\nhsa\\_R\\_adj.csv & csv file with the  adjacency matrix of the reaction graph\\\\\n\\hline\nhsa\\_R\\_nl.csv & csv file with the node (reactions) labels  of the reaction graph\\\\\n\\hline\nhsa\\_RC.graphml & reaction graph  GraphML format\\\\\n\\hline\nhsa\\_RC.pdf & reaction graph pdf graphic\\\\\n\\hline\nhsa\\_RC.svg & reaction graph svg graphic\\\\\n\\hline\nhsa\\_summary.txt & text summary file with the number of MBBs, reactions, etc. in the previous graphs\\\\\n\\hline\n\\end{tabular}\n:::\n:::\n\n\n\n## Pan & core metabolic graphs\n\nPan and core metabolic graphs for every group were generated. For instance, one can read the pan and core metabolic graphs generated for the group Algae in the directory (Groups/Algae).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfiles_Algae=dir(paste0(path_exp,\"Groups/Algae\"))\nfiles_Algae\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"core\" \"pan\" \n```\n:::\n:::\n\n\n\nThe global core reaction graph, which is the core of all the organisms' reaction graphs in this Eukaryotes test, is empty.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph_core_RC=read.graph(\n  paste0(path_exp,\n         \"Global/core/core_RC.graphml\"),\n  format = \"graphml\")\nsummary(graph_core_RC)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIGRAPH 8182f78 D--- 0 0 -- \n+ attr: color (v/c), label (v/c), id (v/c)\n```\n:::\n:::\n\n\n\nThe global core reaction graph has 0 vertex and 0 edges. It is an empty graph.\n\nThe core reaction graph for the Algae group is:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\n  paste0(path_exp,\"Groups/MSA_Cluster_3/core/MSA_Cluster_3_core_RC.pdf\"))\n```\n\n::: {.cell-output-display}\n![Algae core reaction graph](data/result_0a845f74-826e-3b46-aed9-e7ecf74db262/Groups/MSA_Cluster_3/core/MSA_Cluster_3_core_RC.pdf){fig-pos='H' width=100%}\n:::\n:::\n\n\n\nThe global core m-DAG, i.e., the core of all organisms in this example is empty.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph_core_mDAG=read.graph(\n  paste0(path_exp,\"Global/core/core_mDAG.graphml\"),\n  format = \"graphml\")\nsummary(graph_core_mDAG)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIGRAPH 81859ff D--- 0 0 -- \n+ attr: color (v/c), label (v/c), id (v/c)\n```\n:::\n:::\n\n\n\nThe global core m-DAG has 0 vertex and 0 edges. It is an empty graph.\n\nThe core metabolic DAG for the Algae group is:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(paste0(path_exp,                              \"Groups/Algae/core/Algae_core_mDAG.pdf\"))\n```\n\n::: {.cell-output-display}\n![Core m-DAG for Algae](data/result_0a845f74-826e-3b46-aed9-e7ecf74db262/Groups/Algae/core/Algae_core_mDAG.pdf){fig-pos='H' width=100%}\n:::\n:::\n\n\n\nThe global pan reaction graph for the Animals Kingdom is:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph_pan_RC=read.graph(\n  paste0(path_exp,\n         \"TaxonomyLevels/Kingdom/Animals/pan/Animals_pan_RC.graphml\"),\n  format = \"graphml\")\nsummary(graph_pan_RC)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIGRAPH 8195851 D--- 4556 5798 -- \n+ attr: color (v/c), label (v/c), id (v/c), id (e/c)\n```\n:::\n:::\n\n\n\nThis pan reaction graph has 4556 nodes and 5798 edges.\n\n## Graph's topology\n\nFrom the GraphML files, one can extract topological information. Some examples are as follows.\n\nThe diagram below illustrates the distribution of node degrees for an m-DAG.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph_mDAG=read.graph(\n  paste0(path_exp,\n         \"Individuals/hsa/hsa_mDAG.graphml\"),\n  format= \"graphml\")\nsummary(graph_mDAG)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIGRAPH 8197a78 D--- 1026 1086 -- \n+ attr: color (v/c), label (v/c), id (v/c), id (e/c)\n```\n:::\n\n```{.r .cell-code}\nbarplot(table(igraph::degree(graph_mDAG,mode=\"all\")),\n        ylim=c(0,350),col=\"blue\",\n        main=\"Frequency of Node Degrees\",\n        ylab=\"Frequency\",xlab=\"Degree\")\n```\n\n::: {.cell-output-display}\n![](metabolic_graphs_files/figure-pdf/unnamed-chunk-10-1.pdf){fig-pos='H' width=100%}\n:::\n:::\n\n\n\nThe connected components of every graph as well as the size of every connected component can be obtained as:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompo=components(graph_mDAG,mode = \"weak\")\nstr(compo)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nList of 3\n $ membership: num [1:1026] 1 1 1 1 1 1 1 1 1 1 ...\n $ csize     : num [1:167] 589 1 1 1 1 1 4 3 4 3 ...\n $ no        : int 167\n```\n:::\n\n```{.r .cell-code}\ncompo$csize\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1] 589   1   1   1   1   1   4   3   4   3   2   3   3   1   1   1   2   6\n [19]   3   1   3   6   1   1   1   1   1   3   1   6   2   1   1   1   2   1\n [37]   1  14   1  16   1   6   2   2   4   1   1   1   1   1   1   1   1   1\n [55]  13   1   1   1   1   2   6   5   5   2   2  10   1   1   1   2   2   1\n [73]   1   1  62   6   2   1   2   1   1   1   2   1   2  14   3   1   1   1\n [91]   1   1   1   1   1   1   3   6   1   3   1   3   2   1   1   1   2   2\n[109]   3   1   1   2   5   1   1   2   3   2   1   1   2   3   4   1   1   2\n[127]   1   1   2   1   1   1   1   1   3   1   2   2   1   6   1   1   1   2\n[145]   1   1   1   1   1   2   7   1  15   3   1   1   1   1   2   1   3   1\n[163]   1   1   1   1   2\n```\n:::\n\n```{.r .cell-code}\nk=which.max(compo$csize==max(compo$csize))\nk\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n\n```{.r .cell-code}\ntable(compo$membership)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20 \n589   1   1   1   1   1   4   3   4   3   2   3   3   1   1   1   2   6   3   1 \n 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40 \n  3   6   1   1   1   1   1   3   1   6   2   1   1   1   2   1   1  14   1  16 \n 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60 \n  1   6   2   2   4   1   1   1   1   1   1   1   1   1  13   1   1   1   1   2 \n 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80 \n  6   5   5   2   2  10   1   1   1   2   2   1   1   1  62   6   2   1   2   1 \n 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 \n  1   1   2   1   2  14   3   1   1   1   1   1   1   1   1   1   3   6   1   3 \n101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 \n  1   3   2   1   1   1   2   2   3   1   1   2   5   1   1   2   3   2   1   1 \n121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 \n  2   3   4   1   1   2   1   1   2   1   1   1   1   1   3   1   2   2   1   6 \n141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 \n  1   1   1   2   1   1   1   1   1   2   7   1  15   3   1   1   1   1   2   1 \n161 162 163 164 165 166 167 \n  3   1   1   1   1   1   2 \n```\n:::\n\n```{.r .cell-code}\nvertex=which(compo$membership==k)\nlength(vertex)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 589\n```\n:::\n\n```{.r .cell-code}\nBig_Component=induced_subgraph(graph_mDAG, vids=vertex)\nigraph::vcount(Big_Component)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 589\n```\n:::\n\n```{.r .cell-code}\nigraph::ecount(Big_Component)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 774\n```\n:::\n:::\n\n\n\nAnd the plot of the bigger component of the m-DAG in Homo sapiens is:\n\n\n\n::: {.cell layout-align=\"center\" title='Bigger componet of hsa mDAG'}\n\n```{.r .cell-code}\nknitr::include_graphics(paste0(path_exp,\n                               \"Individuals/hsa/hsa_mDAG_biggerDAG.pdf\"))\n```\n\n::: {.cell-output-display}\n![](data/result_0a845f74-826e-3b46-aed9-e7ecf74db262/Individuals/hsa/hsa_mDAG_biggerDAG.pdf){fig-align='center' fig-pos='H' width=100%}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#path_exp=\"data/result_bb261b6e-95c6-3e39-b82b-b68eea80e30b/data/\" \nlist_names=dir(paste0(path_exp,\"Individuals/\"))\nlist_names= list_names[-1] # filter 0000_RefPw\nlength(list_names) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 884\n```\n:::\n\n```{.r .cell-code}\ngraphs_list=paste0(path_exp,\"Individuals/\", list_names,\"/\",list_names, \"_MDAG.graphml\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\n  paste0(path_exp,\"Individuals/cang/cang_RC.pdf\"))\n```\n\n::: {.cell-output-display}\n![](data/result_0a845f74-826e-3b46-aed9-e7ecf74db262/Individuals/cang/cang_RC.pdf){fig-pos='H' width=100%}\n:::\n:::\n\n\n\n## Graph statistics\n\nThe number of connected component in each generated m-DAG with their frequency in the entire set of m-DAGs, can be obtained as follows:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_mDAG=function(x) {DAG=read.graph(file=x,\n                                      format=\"graphml\")\nreturn(DAG)}\nmDAG_componets=function(x) {\n  sort(components(x,mode = \"weak\")$csize,\n       decreasing=TRUE)\n}\n\ncompo_list=lapply(graphs_list,\n                  FUN=function(x) {\n                    gg=read_mDAG(x)\n                    aux=list(\n                      mDAG_componets=mDAG_componets(gg),\n                      degree_count=igraph::degree(gg,mode=\"total\"))\n                    return(aux)}\n)\n\nnames(compo_list)=list_names\nn=max(sapply(compo_list,FUN=function(x) {length(x[[1]])}))\nn\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 234\n```\n:::\n\n```{.r .cell-code}\nsize_compo_list=lapply(compo_list,FUN=function(x) {\n  return(c(x[[1]],rep(NA,n-length(x[[1]]))))})\n\naux=do.call(bind_cols,size_compo_list)\nweak_componets_size=pivot_longer(aux,aaf:zvi,names_to=\"Organism\",\n                                 values_to=\"csize\") %>%\n  arrange(Organism,-csize)\nweak_componets_size$index=rep(1:n,times=dim(aux)[2])\nweak_componets_size=weak_componets_size %>%\n  left_join(meta_taxo,by=\"Organism\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nOrganism=names(compo_list)\nbig_MBB=function(org){\n  org=\"hsa\"\n  x=Results %>% filter(Organism==org)\n  x=as.character(x[1,5:dim(Results)[2]])\n  x=x[x!=\"NA\"]\n  tt=sort(table(x),decreasing=TRUE)\n  return(tt)\n}\nbig_MBB_list= lapply(Organism,FUN=function(x) big_MBB(x))\nnMBB=max(sapply(big_MBB_list,FUN=function(x) length(x)))\nnMBB\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1028\n```\n:::\n\n```{.r .cell-code}\nbig_MBB_list=lapply(big_MBB_list,\n                    FUN=function(x){\n                      x=c(x,rep(NA,nMBB-length(x)))\n                      return(x)}\n)\nnames(big_MBB_list)=Organism\nbig_MBB_list=do.call(bind_cols,big_MBB_list)\n\nkMBB=nrow(big_MBB_list)\nindex=rep(1:kMBB,times=length(Organism))\n\nbig_MBB_list2=pivot_longer(big_MBB_list,\n                           cols=names(big_MBB_list),\n                           values_to = \"MBBsize\",\n                           names_to = \"Organism\") %>% \n  arrange(Organism,-MBBsize) %>%  \n  mutate(index=index) %>% \n  left_join(meta_taxo,by=\"Organism\")\n```\n:::\n\n\n\nWe can visualize the sizes of the weak components for each m-DAG, using colors to represent the different Kingdoms, also we scale the results by a log-log plot:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCOLOR_KINGDOM=c(\"red\",\"yellow\",\"green\",\"black\")\ncolors_kingdom=weak_componets_size%>% select(Organism,Kingdom) %>% distinct()\nnames(COLOR_KINGDOM)=sort(unique(colors_kingdom$Kingdom))\n\np1<- ggplot(data=weak_componets_size) + \n  geom_line(mapping=aes(x=index,\n                        y=csize,group = Organism,\n                        color=Kingdom),\n            na.rm=TRUE) + \n  scale_x_continuous(trans=\"identity\") + \n  scale_y_continuous(trans=\"identity\") +\n  ylim(0,640)+\n  ggtitle(\"Plot of weak components size decreasing order.\")+\n  ylab(\"Weak components size\") + xlab(\"Order\")+\n  scale_color_manual(values =COLOR_KINGDOM[colors_kingdom$Kingdom])\n\np2<- ggplot(data=weak_componets_size) + \n  geom_line(mapping=aes(x=index,\n                        y=csize,group = Organism,\n                        color=Kingdom),\n            na.rm=TRUE) + \n  scale_y_continuous(trans='log10') + \n  scale_x_continuous(trans='log10') +\n  scale_color_manual(values =COLOR_KINGDOM[colors_kingdom$Kingdom])+\n  ggtitle(\"Plot log10-log10 of size  weak components decreasing order.\") +\n  ylab(\"Log10 weak component size\") + xlab(\"Log10 order\")\np1\n```\n\n::: {.cell-output-display}\n![](metabolic_graphs_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H' width=100%}\n:::\n\n```{.r .cell-code}\np2\n```\n\n::: {.cell-output-display}\n![](metabolic_graphs_files/figure-pdf/unnamed-chunk-17-2.pdf){fig-pos='H' width=100%}\n:::\n:::\n\n\n\nA table with the frequencies of the weak connected components sizes, displayed by Kingdom, can be obtained as follows:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naux=table(weak_componets_size$csize,weak_componets_size$Kingdom)\ntable_wcc_size=tibble(Order=1:dim(aux)[1],\n                      Wcc_size=as.integer(unlist(dimnames(aux)[1])),\n                      Animals=aux[,1],\n                      Fungi=aux[,2],\n                      Plants=aux[,3],\n                      Protists=aux[,4])\nknitr::kable(table_wcc_size)\n```\n\n::: {.cell-output-display}\n\\begin{tabular}{r|r|r|r|r|r}\n\\hline\nOrder & Wcc\\_size & Animals & Fungi & Plants & Protists\\\\\n\\hline\n1 & 1 & 57634 & 15311 & 15024 & 4462\\\\\n\\hline\n2 & 2 & 13528 & 2118 & 2908 & 932\\\\\n\\hline\n3 & 3 & 7018 & 1070 & 911 & 317\\\\\n\\hline\n4 & 4 & 2459 & 313 & 292 & 96\\\\\n\\hline\n5 & 5 & 1962 & 215 & 389 & 81\\\\\n\\hline\n6 & 6 & 1778 & 154 & 323 & 49\\\\\n\\hline\n7 & 7 & 633 & 46 & 111 & 15\\\\\n\\hline\n8 & 8 & 278 & 57 & 110 & 7\\\\\n\\hline\n9 & 9 & 174 & 76 & 151 & 22\\\\\n\\hline\n10 & 10 & 671 & 6 & 124 & 7\\\\\n\\hline\n11 & 11 & 411 & 14 & 6 & 20\\\\\n\\hline\n12 & 12 & 109 & 12 & 4 & 5\\\\\n\\hline\n13 & 13 & 369 & 92 & 132 & 7\\\\\n\\hline\n14 & 14 & 774 & 9 & 2 & 2\\\\\n\\hline\n15 & 15 & 234 & 1 & 5 & 6\\\\\n\\hline\n16 & 16 & 79 & 6 & 1 & 1\\\\\n\\hline\n17 & 17 & 55 & 8 & 1 & 1\\\\\n\\hline\n18 & 18 & 4 & 5 & 9 & 5\\\\\n\\hline\n19 & 19 & 5 & 3 & 87 & 4\\\\\n\\hline\n20 & 20 & 9 & 3 & 0 & 1\\\\\n\\hline\n21 & 21 & 13 & 2 & 12 & 1\\\\\n\\hline\n22 & 22 & 7 & 2 & 2 & 0\\\\\n\\hline\n23 & 23 & 21 & 1 & 3 & 0\\\\\n\\hline\n24 & 24 & 19 & 1 & 3 & 1\\\\\n\\hline\n25 & 25 & 20 & 0 & 2 & 1\\\\\n\\hline\n26 & 26 & 12 & 0 & 39 & 0\\\\\n\\hline\n27 & 27 & 1 & 1 & 11 & 0\\\\\n\\hline\n28 & 28 & 5 & 2 & 77 & 0\\\\\n\\hline\n29 & 29 & 40 & 1 & 0 & 1\\\\\n\\hline\n30 & 30 & 0 & 1 & 1 & 0\\\\\n\\hline\n31 & 31 & 72 & 8 & 1 & 0\\\\\n\\hline\n32 & 32 & 11 & 7 & 1 & 0\\\\\n\\hline\n33 & 33 & 1 & 0 & 0 & 2\\\\\n\\hline\n34 & 34 & 6 & 0 & 0 & 0\\\\\n\\hline\n35 & 35 & 2 & 0 & 0 & 0\\\\\n\\hline\n36 & 36 & 3 & 0 & 0 & 0\\\\\n\\hline\n37 & 37 & 5 & 1 & 2 & 0\\\\\n\\hline\n38 & 38 & 0 & 0 & 0 & 1\\\\\n\\hline\n39 & 39 & 5 & 0 & 0 & 0\\\\\n\\hline\n40 & 40 & 5 & 1 & 0 & 0\\\\\n\\hline\n41 & 41 & 4 & 0 & 0 & 0\\\\\n\\hline\n42 & 42 & 1 & 0 & 0 & 0\\\\\n\\hline\n43 & 43 & 2 & 0 & 0 & 1\\\\\n\\hline\n44 & 44 & 6 & 0 & 0 & 0\\\\\n\\hline\n45 & 45 & 1 & 0 & 0 & 0\\\\\n\\hline\n46 & 46 & 5 & 0 & 0 & 0\\\\\n\\hline\n47 & 47 & 9 & 0 & 0 & 0\\\\\n\\hline\n48 & 48 & 1 & 0 & 0 & 0\\\\\n\\hline\n49 & 49 & 1 & 1 & 0 & 0\\\\\n\\hline\n50 & 50 & 1 & 0 & 0 & 0\\\\\n\\hline\n51 & 51 & 4 & 0 & 0 & 0\\\\\n\\hline\n52 & 53 & 50 & 1 & 0 & 1\\\\\n\\hline\n53 & 54 & 6 & 0 & 0 & 0\\\\\n\\hline\n54 & 55 & 1 & 0 & 0 & 0\\\\\n\\hline\n55 & 56 & 8 & 0 & 0 & 0\\\\\n\\hline\n56 & 57 & 2 & 0 & 0 & 0\\\\\n\\hline\n57 & 58 & 12 & 1 & 0 & 0\\\\\n\\hline\n58 & 59 & 6 & 0 & 0 & 0\\\\\n\\hline\n59 & 60 & 30 & 1 & 0 & 0\\\\\n\\hline\n60 & 61 & 5 & 0 & 0 & 0\\\\\n\\hline\n61 & 62 & 15 & 0 & 0 & 0\\\\\n\\hline\n62 & 63 & 4 & 0 & 0 & 0\\\\\n\\hline\n63 & 64 & 2 & 0 & 0 & 0\\\\\n\\hline\n64 & 65 & 34 & 0 & 0 & 0\\\\\n\\hline\n65 & 66 & 6 & 0 & 0 & 0\\\\\n\\hline\n66 & 67 & 1 & 0 & 0 & 0\\\\\n\\hline\n67 & 69 & 1 & 0 & 0 & 0\\\\\n\\hline\n68 & 70 & 2 & 0 & 0 & 1\\\\\n\\hline\n69 & 71 & 1 & 0 & 0 & 0\\\\\n\\hline\n70 & 72 & 1 & 0 & 0 & 0\\\\\n\\hline\n71 & 73 & 6 & 0 & 0 & 0\\\\\n\\hline\n72 & 77 & 2 & 0 & 0 & 1\\\\\n\\hline\n73 & 78 & 1 & 0 & 0 & 1\\\\\n\\hline\n74 & 83 & 0 & 0 & 0 & 2\\\\\n\\hline\n75 & 84 & 1 & 0 & 0 & 0\\\\\n\\hline\n76 & 87 & 1 & 0 & 0 & 0\\\\\n\\hline\n77 & 88 & 1 & 0 & 0 & 1\\\\\n\\hline\n78 & 90 & 2 & 0 & 0 & 1\\\\\n\\hline\n79 & 91 & 1 & 0 & 0 & 0\\\\\n\\hline\n80 & 94 & 4 & 0 & 0 & 1\\\\\n\\hline\n81 & 95 & 1 & 0 & 0 & 0\\\\\n\\hline\n82 & 96 & 1 & 0 & 0 & 1\\\\\n\\hline\n83 & 97 & 0 & 0 & 0 & 1\\\\\n\\hline\n84 & 99 & 1 & 0 & 0 & 1\\\\\n\\hline\n85 & 100 & 2 & 0 & 0 & 0\\\\\n\\hline\n86 & 101 & 1 & 0 & 0 & 0\\\\\n\\hline\n87 & 102 & 0 & 0 & 0 & 1\\\\\n\\hline\n88 & 103 & 3 & 0 & 0 & 1\\\\\n\\hline\n89 & 104 & 0 & 0 & 0 & 2\\\\\n\\hline\n90 & 105 & 0 & 0 & 0 & 1\\\\\n\\hline\n91 & 107 & 0 & 0 & 0 & 1\\\\\n\\hline\n92 & 108 & 1 & 0 & 0 & 2\\\\\n\\hline\n93 & 110 & 2 & 0 & 0 & 0\\\\\n\\hline\n94 & 111 & 1 & 0 & 0 & 0\\\\\n\\hline\n95 & 112 & 0 & 1 & 0 & 0\\\\\n\\hline\n96 & 113 & 2 & 0 & 0 & 0\\\\\n\\hline\n97 & 114 & 1 & 0 & 0 & 1\\\\\n\\hline\n98 & 116 & 1 & 0 & 0 & 0\\\\\n\\hline\n99 & 117 & 3 & 0 & 0 & 0\\\\\n\\hline\n100 & 120 & 1 & 0 & 0 & 0\\\\\n\\hline\n101 & 121 & 2 & 0 & 0 & 0\\\\\n\\hline\n102 & 125 & 1 & 0 & 0 & 0\\\\\n\\hline\n103 & 127 & 1 & 0 & 0 & 1\\\\\n\\hline\n104 & 128 & 0 & 0 & 0 & 2\\\\\n\\hline\n105 & 153 & 0 & 1 & 0 & 0\\\\\n\\hline\n106 & 166 & 0 & 0 & 0 & 1\\\\\n\\hline\n107 & 175 & 0 & 0 & 0 & 2\\\\\n\\hline\n108 & 181 & 0 & 0 & 0 & 1\\\\\n\\hline\n109 & 183 & 0 & 0 & 0 & 2\\\\\n\\hline\n110 & 184 & 1 & 0 & 0 & 0\\\\\n\\hline\n111 & 187 & 0 & 0 & 0 & 1\\\\\n\\hline\n112 & 193 & 1 & 0 & 0 & 1\\\\\n\\hline\n113 & 195 & 0 & 0 & 0 & 1\\\\\n\\hline\n114 & 196 & 0 & 0 & 0 & 1\\\\\n\\hline\n115 & 198 & 1 & 0 & 0 & 0\\\\\n\\hline\n116 & 203 & 0 & 0 & 0 & 1\\\\\n\\hline\n117 & 205 & 0 & 0 & 0 & 1\\\\\n\\hline\n118 & 210 & 2 & 0 & 0 & 0\\\\\n\\hline\n119 & 219 & 1 & 0 & 0 & 1\\\\\n\\hline\n120 & 220 & 1 & 0 & 0 & 0\\\\\n\\hline\n121 & 229 & 1 & 0 & 0 & 0\\\\\n\\hline\n122 & 231 & 0 & 0 & 0 & 1\\\\\n\\hline\n123 & 232 & 1 & 0 & 0 & 0\\\\\n\\hline\n124 & 233 & 0 & 1 & 0 & 0\\\\\n\\hline\n125 & 235 & 1 & 0 & 0 & 0\\\\\n\\hline\n126 & 238 & 3 & 0 & 0 & 0\\\\\n\\hline\n127 & 243 & 1 & 0 & 0 & 0\\\\\n\\hline\n128 & 245 & 0 & 1 & 0 & 0\\\\\n\\hline\n129 & 246 & 1 & 1 & 0 & 0\\\\\n\\hline\n130 & 248 & 0 & 1 & 0 & 0\\\\\n\\hline\n131 & 249 & 0 & 2 & 0 & 0\\\\\n\\hline\n132 & 250 & 0 & 2 & 0 & 0\\\\\n\\hline\n133 & 251 & 0 & 1 & 0 & 0\\\\\n\\hline\n134 & 252 & 1 & 2 & 0 & 0\\\\\n\\hline\n135 & 253 & 1 & 0 & 0 & 0\\\\\n\\hline\n136 & 254 & 0 & 1 & 0 & 0\\\\\n\\hline\n137 & 255 & 2 & 0 & 0 & 0\\\\\n\\hline\n138 & 256 & 2 & 1 & 0 & 0\\\\\n\\hline\n139 & 257 & 4 & 0 & 0 & 0\\\\\n\\hline\n140 & 258 & 1 & 1 & 0 & 0\\\\\n\\hline\n141 & 259 & 1 & 0 & 0 & 0\\\\\n\\hline\n142 & 260 & 2 & 1 & 0 & 1\\\\\n\\hline\n143 & 261 & 2 & 1 & 0 & 0\\\\\n\\hline\n144 & 262 & 2 & 0 & 0 & 0\\\\\n\\hline\n145 & 263 & 4 & 1 & 0 & 1\\\\\n\\hline\n146 & 264 & 4 & 0 & 0 & 0\\\\\n\\hline\n147 & 265 & 3 & 4 & 0 & 2\\\\\n\\hline\n148 & 266 & 2 & 1 & 0 & 0\\\\\n\\hline\n149 & 267 & 2 & 1 & 0 & 0\\\\\n\\hline\n150 & 268 & 2 & 3 & 0 & 1\\\\\n\\hline\n151 & 269 & 3 & 1 & 0 & 0\\\\\n\\hline\n152 & 270 & 3 & 0 & 1 & 0\\\\\n\\hline\n153 & 271 & 1 & 1 & 0 & 0\\\\\n\\hline\n154 & 272 & 2 & 2 & 0 & 0\\\\\n\\hline\n155 & 273 & 4 & 3 & 0 & 1\\\\\n\\hline\n156 & 274 & 2 & 1 & 0 & 0\\\\\n\\hline\n157 & 275 & 4 & 2 & 0 & 0\\\\\n\\hline\n158 & 276 & 0 & 2 & 0 & 0\\\\\n\\hline\n159 & 277 & 4 & 4 & 0 & 0\\\\\n\\hline\n160 & 278 & 3 & 3 & 0 & 1\\\\\n\\hline\n161 & 279 & 5 & 0 & 0 & 1\\\\\n\\hline\n162 & 280 & 1 & 0 & 0 & 0\\\\\n\\hline\n163 & 281 & 3 & 4 & 0 & 0\\\\\n\\hline\n164 & 282 & 4 & 1 & 0 & 0\\\\\n\\hline\n165 & 283 & 5 & 1 & 0 & 0\\\\\n\\hline\n166 & 284 & 4 & 1 & 0 & 0\\\\\n\\hline\n167 & 285 & 5 & 1 & 0 & 0\\\\\n\\hline\n168 & 286 & 4 & 2 & 0 & 1\\\\\n\\hline\n169 & 287 & 1 & 0 & 0 & 0\\\\\n\\hline\n170 & 288 & 2 & 3 & 0 & 0\\\\\n\\hline\n171 & 289 & 1 & 0 & 0 & 0\\\\\n\\hline\n172 & 290 & 3 & 0 & 0 & 0\\\\\n\\hline\n173 & 291 & 1 & 1 & 0 & 0\\\\\n\\hline\n174 & 292 & 1 & 3 & 0 & 1\\\\\n\\hline\n175 & 293 & 5 & 1 & 0 & 0\\\\\n\\hline\n176 & 294 & 6 & 0 & 0 & 0\\\\\n\\hline\n177 & 295 & 1 & 2 & 0 & 0\\\\\n\\hline\n178 & 296 & 5 & 1 & 0 & 0\\\\\n\\hline\n179 & 297 & 4 & 1 & 0 & 0\\\\\n\\hline\n180 & 298 & 2 & 1 & 0 & 0\\\\\n\\hline\n181 & 299 & 2 & 0 & 1 & 1\\\\\n\\hline\n182 & 300 & 2 & 0 & 0 & 0\\\\\n\\hline\n183 & 301 & 4 & 2 & 0 & 0\\\\\n\\hline\n184 & 302 & 1 & 0 & 0 & 1\\\\\n\\hline\n185 & 303 & 3 & 0 & 0 & 0\\\\\n\\hline\n186 & 304 & 3 & 0 & 0 & 0\\\\\n\\hline\n187 & 305 & 3 & 0 & 0 & 0\\\\\n\\hline\n188 & 306 & 2 & 1 & 0 & 0\\\\\n\\hline\n189 & 307 & 4 & 1 & 0 & 0\\\\\n\\hline\n190 & 308 & 1 & 0 & 0 & 0\\\\\n\\hline\n191 & 310 & 1 & 0 & 0 & 0\\\\\n\\hline\n192 & 311 & 1 & 0 & 1 & 0\\\\\n\\hline\n193 & 313 & 2 & 2 & 0 & 0\\\\\n\\hline\n194 & 315 & 1 & 0 & 0 & 0\\\\\n\\hline\n195 & 316 & 1 & 0 & 0 & 0\\\\\n\\hline\n196 & 317 & 1 & 0 & 1 & 0\\\\\n\\hline\n197 & 318 & 0 & 2 & 0 & 0\\\\\n\\hline\n198 & 319 & 1 & 0 & 0 & 0\\\\\n\\hline\n199 & 320 & 3 & 1 & 1 & 0\\\\\n\\hline\n200 & 321 & 1 & 0 & 0 & 0\\\\\n\\hline\n201 & 322 & 3 & 0 & 0 & 0\\\\\n\\hline\n202 & 323 & 2 & 0 & 0 & 0\\\\\n\\hline\n203 & 325 & 1 & 0 & 0 & 0\\\\\n\\hline\n204 & 327 & 2 & 1 & 0 & 0\\\\\n\\hline\n205 & 328 & 5 & 1 & 1 & 0\\\\\n\\hline\n206 & 330 & 0 & 1 & 0 & 0\\\\\n\\hline\n207 & 332 & 1 & 0 & 0 & 0\\\\\n\\hline\n208 & 333 & 1 & 1 & 1 & 1\\\\\n\\hline\n209 & 335 & 1 & 0 & 0 & 0\\\\\n\\hline\n210 & 338 & 1 & 0 & 0 & 0\\\\\n\\hline\n211 & 339 & 0 & 0 & 1 & 1\\\\\n\\hline\n212 & 340 & 1 & 1 & 0 & 0\\\\\n\\hline\n213 & 341 & 1 & 0 & 0 & 0\\\\\n\\hline\n214 & 342 & 1 & 0 & 0 & 1\\\\\n\\hline\n215 & 343 & 2 & 1 & 0 & 0\\\\\n\\hline\n216 & 344 & 0 & 0 & 1 & 0\\\\\n\\hline\n217 & 345 & 2 & 0 & 0 & 0\\\\\n\\hline\n218 & 346 & 1 & 0 & 0 & 0\\\\\n\\hline\n219 & 347 & 2 & 0 & 0 & 0\\\\\n\\hline\n220 & 349 & 2 & 0 & 0 & 0\\\\\n\\hline\n221 & 350 & 1 & 0 & 0 & 0\\\\\n\\hline\n222 & 351 & 1 & 0 & 0 & 0\\\\\n\\hline\n223 & 352 & 3 & 0 & 0 & 0\\\\\n\\hline\n224 & 353 & 1 & 0 & 0 & 0\\\\\n\\hline\n225 & 354 & 1 & 0 & 0 & 0\\\\\n\\hline\n226 & 355 & 2 & 0 & 0 & 0\\\\\n\\hline\n227 & 356 & 1 & 1 & 0 & 0\\\\\n\\hline\n228 & 357 & 1 & 2 & 0 & 0\\\\\n\\hline\n229 & 358 & 2 & 1 & 0 & 0\\\\\n\\hline\n230 & 359 & 0 & 0 & 1 & 0\\\\\n\\hline\n231 & 360 & 1 & 0 & 1 & 0\\\\\n\\hline\n232 & 361 & 1 & 3 & 0 & 0\\\\\n\\hline\n233 & 362 & 1 & 2 & 0 & 0\\\\\n\\hline\n234 & 363 & 2 & 3 & 0 & 0\\\\\n\\hline\n235 & 365 & 2 & 1 & 0 & 0\\\\\n\\hline\n236 & 366 & 1 & 0 & 0 & 0\\\\\n\\hline\n237 & 367 & 1 & 0 & 0 & 0\\\\\n\\hline\n238 & 368 & 2 & 1 & 0 & 0\\\\\n\\hline\n239 & 369 & 3 & 1 & 0 & 0\\\\\n\\hline\n240 & 370 & 0 & 2 & 0 & 0\\\\\n\\hline\n241 & 371 & 0 & 2 & 0 & 0\\\\\n\\hline\n242 & 372 & 1 & 0 & 0 & 0\\\\\n\\hline\n243 & 373 & 2 & 2 & 0 & 0\\\\\n\\hline\n244 & 374 & 3 & 1 & 0 & 0\\\\\n\\hline\n245 & 375 & 2 & 1 & 0 & 0\\\\\n\\hline\n246 & 376 & 0 & 1 & 0 & 0\\\\\n\\hline\n247 & 377 & 0 & 1 & 0 & 0\\\\\n\\hline\n248 & 378 & 2 & 0 & 0 & 0\\\\\n\\hline\n249 & 380 & 0 & 3 & 0 & 0\\\\\n\\hline\n250 & 381 & 2 & 1 & 0 & 0\\\\\n\\hline\n251 & 382 & 2 & 1 & 0 & 0\\\\\n\\hline\n252 & 383 & 3 & 1 & 1 & 0\\\\\n\\hline\n253 & 384 & 0 & 1 & 0 & 0\\\\\n\\hline\n254 & 385 & 0 & 1 & 0 & 0\\\\\n\\hline\n255 & 387 & 2 & 2 & 0 & 0\\\\\n\\hline\n256 & 388 & 1 & 2 & 0 & 0\\\\\n\\hline\n257 & 389 & 1 & 0 & 0 & 0\\\\\n\\hline\n258 & 391 & 2 & 0 & 0 & 0\\\\\n\\hline\n259 & 392 & 0 & 1 & 0 & 0\\\\\n\\hline\n260 & 393 & 1 & 1 & 0 & 0\\\\\n\\hline\n261 & 394 & 3 & 0 & 0 & 0\\\\\n\\hline\n262 & 396 & 1 & 0 & 0 & 0\\\\\n\\hline\n263 & 397 & 0 & 2 & 0 & 0\\\\\n\\hline\n264 & 398 & 2 & 0 & 0 & 0\\\\\n\\hline\n265 & 399 & 1 & 1 & 0 & 0\\\\\n\\hline\n266 & 400 & 0 & 0 & 1 & 0\\\\\n\\hline\n267 & 401 & 1 & 1 & 0 & 0\\\\\n\\hline\n268 & 402 & 0 & 1 & 0 & 0\\\\\n\\hline\n269 & 404 & 1 & 1 & 0 & 0\\\\\n\\hline\n270 & 405 & 3 & 1 & 0 & 0\\\\\n\\hline\n271 & 406 & 0 & 1 & 0 & 0\\\\\n\\hline\n272 & 407 & 0 & 2 & 0 & 0\\\\\n\\hline\n273 & 408 & 1 & 1 & 1 & 0\\\\\n\\hline\n274 & 409 & 2 & 0 & 0 & 0\\\\\n\\hline\n275 & 411 & 3 & 0 & 0 & 0\\\\\n\\hline\n276 & 412 & 1 & 0 & 0 & 0\\\\\n\\hline\n277 & 413 & 2 & 1 & 0 & 0\\\\\n\\hline\n278 & 415 & 1 & 0 & 0 & 0\\\\\n\\hline\n279 & 416 & 2 & 0 & 0 & 0\\\\\n\\hline\n280 & 417 & 0 & 1 & 0 & 0\\\\\n\\hline\n281 & 418 & 0 & 1 & 0 & 0\\\\\n\\hline\n282 & 419 & 0 & 1 & 0 & 0\\\\\n\\hline\n283 & 420 & 0 & 1 & 0 & 0\\\\\n\\hline\n284 & 421 & 1 & 2 & 0 & 0\\\\\n\\hline\n285 & 423 & 0 & 2 & 0 & 0\\\\\n\\hline\n286 & 424 & 0 & 1 & 0 & 0\\\\\n\\hline\n287 & 426 & 2 & 0 & 0 & 0\\\\\n\\hline\n288 & 428 & 1 & 0 & 0 & 0\\\\\n\\hline\n289 & 431 & 0 & 1 & 0 & 0\\\\\n\\hline\n290 & 432 & 1 & 0 & 0 & 0\\\\\n\\hline\n291 & 433 & 3 & 0 & 0 & 0\\\\\n\\hline\n292 & 435 & 1 & 0 & 0 & 0\\\\\n\\hline\n293 & 438 & 0 & 1 & 0 & 0\\\\\n\\hline\n294 & 439 & 0 & 1 & 0 & 0\\\\\n\\hline\n295 & 443 & 1 & 0 & 0 & 0\\\\\n\\hline\n296 & 444 & 1 & 0 & 0 & 0\\\\\n\\hline\n297 & 445 & 2 & 1 & 0 & 0\\\\\n\\hline\n298 & 446 & 2 & 0 & 0 & 0\\\\\n\\hline\n299 & 447 & 1 & 0 & 0 & 0\\\\\n\\hline\n300 & 452 & 1 & 0 & 0 & 0\\\\\n\\hline\n301 & 453 & 1 & 0 & 0 & 0\\\\\n\\hline\n302 & 455 & 1 & 0 & 0 & 0\\\\\n\\hline\n303 & 459 & 1 & 0 & 0 & 0\\\\\n\\hline\n304 & 462 & 1 & 0 & 0 & 0\\\\\n\\hline\n305 & 463 & 2 & 0 & 0 & 0\\\\\n\\hline\n306 & 465 & 1 & 0 & 0 & 0\\\\\n\\hline\n307 & 468 & 1 & 0 & 0 & 0\\\\\n\\hline\n308 & 470 & 1 & 0 & 0 & 0\\\\\n\\hline\n309 & 471 & 0 & 0 & 1 & 0\\\\\n\\hline\n310 & 473 & 0 & 0 & 1 & 0\\\\\n\\hline\n311 & 475 & 2 & 0 & 0 & 0\\\\\n\\hline\n312 & 480 & 1 & 0 & 0 & 0\\\\\n\\hline\n313 & 481 & 1 & 0 & 0 & 0\\\\\n\\hline\n314 & 482 & 1 & 0 & 0 & 0\\\\\n\\hline\n315 & 483 & 1 & 0 & 0 & 0\\\\\n\\hline\n316 & 485 & 0 & 0 & 1 & 0\\\\\n\\hline\n317 & 487 & 1 & 0 & 0 & 0\\\\\n\\hline\n318 & 491 & 3 & 0 & 0 & 0\\\\\n\\hline\n319 & 492 & 1 & 0 & 0 & 0\\\\\n\\hline\n320 & 493 & 3 & 0 & 0 & 0\\\\\n\\hline\n321 & 496 & 2 & 0 & 0 & 0\\\\\n\\hline\n322 & 497 & 3 & 0 & 0 & 0\\\\\n\\hline\n323 & 500 & 0 & 0 & 1 & 0\\\\\n\\hline\n324 & 501 & 1 & 0 & 0 & 0\\\\\n\\hline\n325 & 502 & 5 & 0 & 0 & 0\\\\\n\\hline\n326 & 503 & 1 & 0 & 0 & 0\\\\\n\\hline\n327 & 504 & 1 & 0 & 1 & 0\\\\\n\\hline\n328 & 507 & 2 & 0 & 0 & 0\\\\\n\\hline\n329 & 508 & 2 & 0 & 0 & 0\\\\\n\\hline\n330 & 509 & 1 & 0 & 0 & 0\\\\\n\\hline\n331 & 510 & 1 & 0 & 0 & 0\\\\\n\\hline\n332 & 511 & 2 & 0 & 0 & 0\\\\\n\\hline\n333 & 512 & 5 & 0 & 0 & 0\\\\\n\\hline\n334 & 513 & 2 & 0 & 0 & 0\\\\\n\\hline\n335 & 514 & 0 & 0 & 2 & 0\\\\\n\\hline\n336 & 515 & 4 & 0 & 5 & 0\\\\\n\\hline\n337 & 516 & 4 & 0 & 0 & 0\\\\\n\\hline\n338 & 517 & 5 & 0 & 1 & 0\\\\\n\\hline\n339 & 518 & 1 & 0 & 0 & 0\\\\\n\\hline\n340 & 519 & 3 & 0 & 1 & 0\\\\\n\\hline\n341 & 520 & 2 & 0 & 0 & 0\\\\\n\\hline\n342 & 521 & 2 & 0 & 1 & 0\\\\\n\\hline\n343 & 523 & 5 & 0 & 1 & 0\\\\\n\\hline\n344 & 524 & 3 & 0 & 1 & 0\\\\\n\\hline\n345 & 525 & 2 & 0 & 1 & 0\\\\\n\\hline\n346 & 526 & 0 & 0 & 1 & 0\\\\\n\\hline\n347 & 527 & 2 & 0 & 0 & 0\\\\\n\\hline\n348 & 528 & 2 & 0 & 4 & 0\\\\\n\\hline\n349 & 529 & 7 & 0 & 0 & 0\\\\\n\\hline\n350 & 530 & 1 & 0 & 2 & 0\\\\\n\\hline\n351 & 531 & 2 & 0 & 1 & 0\\\\\n\\hline\n352 & 532 & 2 & 0 & 2 & 0\\\\\n\\hline\n353 & 533 & 2 & 0 & 2 & 0\\\\\n\\hline\n354 & 534 & 2 & 0 & 0 & 0\\\\\n\\hline\n355 & 535 & 2 & 0 & 2 & 0\\\\\n\\hline\n356 & 536 & 2 & 0 & 0 & 0\\\\\n\\hline\n357 & 537 & 1 & 0 & 0 & 0\\\\\n\\hline\n358 & 538 & 3 & 0 & 0 & 0\\\\\n\\hline\n359 & 539 & 1 & 0 & 1 & 0\\\\\n\\hline\n360 & 540 & 0 & 0 & 4 & 0\\\\\n\\hline\n361 & 541 & 2 & 0 & 0 & 0\\\\\n\\hline\n362 & 542 & 0 & 0 & 2 & 0\\\\\n\\hline\n363 & 544 & 0 & 0 & 3 & 0\\\\\n\\hline\n364 & 545 & 0 & 0 & 1 & 0\\\\\n\\hline\n365 & 546 & 1 & 0 & 1 & 0\\\\\n\\hline\n366 & 547 & 0 & 0 & 1 & 0\\\\\n\\hline\n367 & 548 & 1 & 0 & 1 & 0\\\\\n\\hline\n368 & 549 & 1 & 0 & 2 & 0\\\\\n\\hline\n369 & 550 & 0 & 0 & 6 & 0\\\\\n\\hline\n370 & 551 & 4 & 0 & 2 & 0\\\\\n\\hline\n371 & 553 & 1 & 0 & 1 & 0\\\\\n\\hline\n372 & 554 & 0 & 0 & 3 & 0\\\\\n\\hline\n373 & 555 & 2 & 0 & 9 & 0\\\\\n\\hline\n374 & 556 & 0 & 0 & 1 & 0\\\\\n\\hline\n375 & 557 & 2 & 0 & 4 & 0\\\\\n\\hline\n376 & 558 & 0 & 0 & 2 & 0\\\\\n\\hline\n377 & 559 & 1 & 0 & 3 & 0\\\\\n\\hline\n378 & 560 & 1 & 0 & 4 & 0\\\\\n\\hline\n379 & 561 & 0 & 0 & 4 & 0\\\\\n\\hline\n380 & 562 & 3 & 0 & 2 & 0\\\\\n\\hline\n381 & 563 & 3 & 0 & 0 & 0\\\\\n\\hline\n382 & 564 & 1 & 0 & 2 & 0\\\\\n\\hline\n383 & 565 & 1 & 0 & 0 & 0\\\\\n\\hline\n384 & 566 & 0 & 0 & 1 & 0\\\\\n\\hline\n385 & 567 & 3 & 0 & 3 & 0\\\\\n\\hline\n386 & 568 & 3 & 0 & 0 & 0\\\\\n\\hline\n387 & 569 & 5 & 0 & 1 & 0\\\\\n\\hline\n388 & 570 & 4 & 0 & 2 & 0\\\\\n\\hline\n389 & 571 & 2 & 0 & 2 & 0\\\\\n\\hline\n390 & 572 & 1 & 0 & 2 & 0\\\\\n\\hline\n391 & 573 & 2 & 0 & 2 & 0\\\\\n\\hline\n392 & 574 & 2 & 0 & 4 & 0\\\\\n\\hline\n393 & 575 & 5 & 0 & 4 & 0\\\\\n\\hline\n394 & 576 & 6 & 0 & 1 & 0\\\\\n\\hline\n395 & 577 & 7 & 0 & 4 & 0\\\\\n\\hline\n396 & 578 & 7 & 0 & 0 & 0\\\\\n\\hline\n397 & 579 & 2 & 0 & 0 & 0\\\\\n\\hline\n398 & 580 & 3 & 0 & 0 & 0\\\\\n\\hline\n399 & 581 & 3 & 0 & 3 & 0\\\\\n\\hline\n400 & 582 & 7 & 0 & 2 & 0\\\\\n\\hline\n401 & 583 & 2 & 0 & 0 & 0\\\\\n\\hline\n402 & 584 & 3 & 0 & 1 & 0\\\\\n\\hline\n403 & 585 & 4 & 0 & 0 & 0\\\\\n\\hline\n404 & 586 & 3 & 0 & 0 & 0\\\\\n\\hline\n405 & 587 & 1 & 0 & 1 & 0\\\\\n\\hline\n406 & 588 & 1 & 0 & 0 & 0\\\\\n\\hline\n407 & 589 & 1 & 0 & 0 & 0\\\\\n\\hline\n408 & 590 & 1 & 0 & 0 & 0\\\\\n\\hline\n409 & 591 & 5 & 0 & 0 & 0\\\\\n\\hline\n410 & 592 & 2 & 0 & 0 & 0\\\\\n\\hline\n411 & 594 & 3 & 0 & 0 & 0\\\\\n\\hline\n412 & 595 & 2 & 0 & 0 & 0\\\\\n\\hline\n413 & 597 & 0 & 0 & 1 & 0\\\\\n\\hline\n414 & 598 & 2 & 0 & 0 & 0\\\\\n\\hline\n415 & 601 & 2 & 0 & 0 & 0\\\\\n\\hline\n416 & 602 & 1 & 0 & 0 & 0\\\\\n\\hline\n417 & 603 & 1 & 0 & 0 & 0\\\\\n\\hline\n418 & 604 & 2 & 0 & 0 & 0\\\\\n\\hline\n419 & 605 & 1 & 0 & 0 & 0\\\\\n\\hline\n420 & 611 & 1 & 0 & 0 & 0\\\\\n\\hline\n421 & 618 & 1 & 0 & 0 & 0\\\\\n\\hline\n422 & 640 & 1 & 0 & 0 & 0\\\\\n\\hline\n\\end{tabular}\n:::\n:::\n\n\n\nA table with the frequencies of the MBBs sizes displayed by Kingdom can be obtained as follows:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naux=table(big_MBB_list2$MBBsize,big_MBB_list2$Kingdom)\ntable_MBB_size=tibble(Order=1:dim(aux)[1],\n                      MBB_size=as.integer(unlist(dimnames(aux)[1])),\n                      Animals=aux[,1],\n                      Fungi=aux[,2],\n                      Plants=aux[,3],\n                      Protists=aux[,4])\nknitr::kable(table_MBB_size)\n```\n\n::: {.cell-output-display}\n\\begin{tabular}{r|r|r|r|r|r}\n\\hline\nOrder & MBB\\_size & Animals & Fungi & Plants & Protists\\\\\n\\hline\n1 & 1 & 511995 & 147378 & 133023 & 53592\\\\\n\\hline\n2 & 2 & 18725 & 5390 & 4865 & 1960\\\\\n\\hline\n3 & 3 & 3745 & 1078 & 973 & 392\\\\\n\\hline\n4 & 4 & 5885 & 1694 & 1529 & 616\\\\\n\\hline\n5 & 5 & 535 & 154 & 139 & 56\\\\\n\\hline\n6 & 6 & 3210 & 924 & 834 & 336\\\\\n\\hline\n7 & 7 & 1605 & 462 & 417 & 168\\\\\n\\hline\n8 & 8 & 535 & 154 & 139 & 56\\\\\n\\hline\n9 & 9 & 535 & 154 & 139 & 56\\\\\n\\hline\n10 & 10 & 535 & 154 & 139 & 56\\\\\n\\hline\n11 & 12 & 1070 & 308 & 278 & 112\\\\\n\\hline\n12 & 18 & 535 & 154 & 139 & 56\\\\\n\\hline\n13 & 30 & 535 & 154 & 139 & 56\\\\\n\\hline\n14 & 979 & 535 & 154 & 139 & 56\\\\\n\\hline\n\\end{tabular}\n:::\n:::\n\n\n",
    "supporting": [
      "metabolic_graphs_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}