project:
  type: book
  output-dir: docs

book:
  title: "A Guide to Interpreting the Results of MetaDAG Analysis"
  author: ""
  date: ""
  chapters:
    - index.qmd
    - load_data.qmd
    - metabolic_graphs.qmd
    - m_DAGs_similarity.qmd
    - cluster_analysis.qmd
    - appendix.qmd
    
format:
  html:
    theme: Journal
    code-fold: false
    cde-summary: "Show the code"
    code-tools: true
    code-overflow: wrap
    highlight-style: github
  pdf:
    toc: true
    toccolor: blue
    output-file: pdf-book
    highlight-style: atom-one-dark
    number-sections: true
    colorlinks: true
    include-in-header:
      - text: |
          \usepackage{svg}
    
editor: visual


