project:
  type: book
  output-dir: docs

book:
  title: "MetaDAG experiment example"
  author: "Version beta 0.2"
  date: "`r format(Sys.time(), '%d %B, %Y')`"
  chapters:
    - index.qmd  
    
format:
  html:
    theme: Journal
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    
editor: visual
