project:
  type: book
  output-dir: docs

book:
  title: "A Guide to Interpreting the Results of MetaDAG Analysis"
  author: ""
  date: ""
  chapters:
    - index.qmd
    
format:
  html:
    theme: Journal
  pdf:
    toc: true
    toccolor: blue
    highlight-style: atom-one-dark
    number-sections: true
    colorlinks: true
    include-in-header:
      - text: |
          \usepackage{svg}
    
editor: visual
