project:
  type: book
  output-dir: docs

book:
  title: "MetaDAG experiment example"
  author: "Version beta 0.2"
  date: "2023-10-03"
  chapters:
    - index.qmd
    
format:
  html:
    theme: Journal
  pdf:
    toc: true
    toccolor: blue
    highlight-style: atom-one-dark
    number-sections: true
    colorlinks: true
    include-in-header:
      - text: |
          \usepackage{svg}
    
editor: visual
