# Similarity comparisons

## Comparison four similarity  mDag eukaryote

Load the similarities for pairs and comparison

```{r}
library(gtools)
library(tidyverse)
load("Similarities.Rdata")
ls(pattern="^Sim")
n=length(meta_taxo$mDAG_Id)
dim(Sim_MSA_mDAG)
aux1=base::rep(x=1:n,each=c(n:1))

aux=as_tibble(Sim_MSA_mDAG)
aux$mDag=names(aux)
<<<<<<< HEAD
aux=aux %>% pivot_longer(cols=`0576`:`0036`,
                         names_to="mDag_2",values_to="sim_MSA")
aux_2= aux %>%  mutate(i=pmax(as.integer(mDag),as.integer(mDag_2)),
                       j=pmin(as.integer(mDag),as.integer(mDag_2)))%>%
  unite("ij",i:j) %>% filter(duplicated(ij))
=======
aux=aux %>% pivot_longer(cols=`0576`:`0036`,names_to="mDag_2",values_to="dis_MSA")

aux_2= aux %>%  mutate(i=pmax(as.integer(mDag),as.integer(mDag_2)),j=pmin(as.integer(mDag),as.integer(mDag_2))) %>% unite("ij",i:j) %>% filter(duplicated(ij))
>>>>>>> cfce73af3d68b86a906aefe6aaab2f0b812ade2d

aux=as_tibble(Sim_Mun_mDAG)
aux$mDag=names(aux)
aux=aux %>% pivot_longer(cols=`0576`:`0036`,names_to="mDag_2",values_to="Sim_Mun")
aux_2 = aux_2 %>% left_join(aux)


aux=as_tibble(Sim_MSA_Mun_mDAG)
aux$mDag=names(aux)
aux=aux %>% pivot_longer(cols=`0576`:`0036`,names_to="mDag_2",values_to="sim_MSA_Mun")
aux_2 = aux_2 %>% left_join(aux)

aux=as_tibble(Sim_Mun_MSA_mDAG)
aux$mDag=names(aux)
aux=aux %>% pivot_longer(cols=`0576`:`0036`,names_to="mDag_2",values_to="sim_Mun_MSA")
aux_2 = aux_2 %>% left_join(aux)
Sim_comp=aux_2[,c(1,2,4,3,5:7)]
rm(aux,aux_2)
```

**Tablas de las correlaciones de Spearman y Pearson entre las 4 similitudes.**

```{r}
cor(Sim_comp[,4:7],method="spearman")



cor(Sim_comp[,4:7],method="pearson")
```


```{r cache=TRUE}
library(GGally)
ggpairs(Sim_comp[,4:7])
```

```{r}
boxplot(Sim_comp[,4:7])
```

