{
  "hash": "b2437608598541868492c30b91116c10",
  "result": {
    "engine": "knitr",
    "markdown": "# Load data\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexperiment=\n  \"result_0a845f74-826e-3b46-aed9-e7ecf74db262/\"\npath_exp=paste0(\"data/\",experiment)\nknitr::kable(data.frame(\n  Directory_files_and_folders=dir(path_exp),\n  Type=c(rep(\"Data file\",2),\n         rep(\"Directory\",3),\n         rep(\"Data file\",6),\n         \"Directory\")))\n```\n\n::: {.cell-output-display}\n\n\n|Directory_files_and_folders         |Type      |\n|:-----------------------------------|:---------|\n|Different_MBB.csv                   |Data file |\n|Different_mDAG.csv                  |Data file |\n|Global                              |Directory |\n|Groups                              |Directory |\n|Individuals                         |Directory |\n|Report.pdf                          |Data file |\n|Results.csv                         |Data file |\n|Similarities_MBB_MSAMethod.csv      |Data file |\n|Similarities_MBB_MunkresMethod.csv  |Data file |\n|Similarities_mDAG_MSAMethod.csv     |Data file |\n|Similarities_mDAG_MunkresMethod.csv |Data file |\n|TaxonomyLevels                      |Directory |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nMBB=read_csv(paste0(path_exp,\"Different_MBB.csv\"),\n             show_col_types = FALSE)\nmDAG=read_csv(paste0(path_exp,\"Different_mDAG.csv\"),\n              show_col_types = FALSE)\n```\n:::\n\n\n\n\n\n\n## Load metadata\n\nOrganisms are sorted by Kingdom, Phylum and Class:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath_exp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data/result_0a845f74-826e-3b46-aed9-e7ecf74db262/\"\n```\n\n\n:::\n\n```{.r .cell-code}\nResults=read_csv(paste0(path_exp,\"Results.csv\"))\n#rename MetaDaG variables\nnames(Results)[c(1,2,3,4,5)]=c(\"Organism\",\"Categories\",\"Groups\",\"mDAG_Id\",\"Full_Name\")\ntaxo=Results %>% select(Organism:Full_Name)\nmeta_taxo=taxo %>% separate(Categories,into=c(\"Kingdom\",\"Phylum\",\"Class\"))\nindex=which(is.na(meta_taxo$Class))\nmeta_taxo$Class[index]=paste(meta_taxo$Phylum[index])\nrm(taxo)\naux=table(meta_taxo$Kingdom)\nFreq_Kingdom=tibble(Kingdom=names(aux),Freq_Kingdom=aux)\naux=table(meta_taxo$Phylum)\nFreq_Phylum=tibble(Phylum=names(aux),Freq_Phylum=aux)\naux=table(meta_taxo$Class)\nFreq_Class=tibble(Class=names(aux),Freq_Class=aux)\n\nmeta_taxo = meta_taxo %>%\n    left_join(Freq_Kingdom) %>% \n  left_join(Freq_Phylum) %>%\n  left_join(Freq_Class)\nmeta_taxo = meta_taxo %>% \n  arrange(desc(Freq_Kingdom),\n          desc(Freq_Phylum),\n          desc(Freq_Class))\n\n#arrange metaxto by frequencies of kingom phylum and class\n\n\nknitr::kable(head(meta_taxo))\n```\n\n::: {.cell-output-display}\n\n\n|Organism |Kingdom |Phylum      |Class   |Groups    |mDAG_Id |Full_Name                                        | Freq_Kingdom| Freq_Phylum| Freq_Class|\n|:--------|:-------|:-----------|:-------|:---------|:-------|:------------------------------------------------|------------:|-----------:|----------:|\n|aamp     |Animals |Vertebrates |Mammals |Cluster 1 |0313    |Arvicola amphibius (Eurasian water vole)         |          535|         331|        139|\n|afz      |Animals |Vertebrates |Mammals |Cluster 1 |0143    |Antechinus flavipes (yellow-footed antechinus)   |          535|         331|        139|\n|ajm      |Animals |Vertebrates |Mammals |Cluster 1 |0221    |Artibeus jamaicensis (Jamaican fruit-eating bat) |          535|         331|        139|\n|aju      |Animals |Vertebrates |Mammals |Cluster 1 |0224    |Acinonyx jubatus (cheetah)                       |          535|         331|        139|\n|aml      |Animals |Vertebrates |Mammals |Cluster 1 |0279    |Ailuropoda melanoleuca (giant panda)             |          535|         331|        139|\n|anu      |Animals |Vertebrates |Mammals |Cluster 1 |0310    |Arvicanthis niloticus (African grass rat)        |          535|         331|        139|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(meta_taxo$Kingdom) %>% kable %>%\n  kable_styling(\"striped\", full_width = F,position=\"left\")%>% \n  scroll_box(width = \"400px\", height = \"200px\")\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[l]{lr}\n\\toprule\nVar1 & Freq\\\\\n\\midrule\nAnimals & 535\\\\\nFungi & 154\\\\\nPlants & 139\\\\\nProtists & 56\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n\n```{.r .cell-code}\ntable(meta_taxo$Phylum,meta_taxo$Kingdom) %>% kable %>%\n  kable_styling(\"striped\", full_width = F,position=\"left\")%>% \n  scroll_box(width = \"500px\", height = \"500px\")\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[l]{lrrrr}\n\\toprule\n & Animals & Fungi & Plants & Protists\\\\\n\\midrule\nAlveolates & 0 & 0 & 0 & 25\\\\\nAmoebozoa & 0 & 0 & 0 & 7\\\\\nAnnelids & 1 & 0 & 0 & 0\\\\\nArthropods & 158 & 0 & 0 & 0\\\\\nAscomycetes & 0 & 113 & 0 & 0\\\\\n\\addlinespace\nBasal & 0 & 0 & 2 & 0\\\\\nBasidiomycetes & 0 & 36 & 0 & 0\\\\\nBrachiopodas & 1 & 0 & 0 & 0\\\\\nCephalochordates & 2 & 0 & 0 & 0\\\\\nChoanoflagellates & 0 & 0 & 0 & 2\\\\\n\\addlinespace\nCnidarians & 10 & 0 & 0 & 0\\\\\nCryptomonads & 0 & 0 & 0 & 1\\\\\nEchinoderms & 3 & 0 & 0 & 0\\\\\nEudicots & 0 & 0 & 98 & 0\\\\\nEuglenozoa & 0 & 0 & 0 & 9\\\\\n\\addlinespace\nFerns & 0 & 0 & 1 & 0\\\\\nFlatworms & 4 & 0 & 0 & 0\\\\\nGreen & 0 & 0 & 11 & 0\\\\\nHaptophyta & 0 & 0 & 0 & 1\\\\\nHemichordates & 1 & 0 & 0 & 0\\\\\n\\addlinespace\nHeterolobosea & 0 & 0 & 0 & 1\\\\\nMetamonada & 0 & 0 & 0 & 2\\\\\nMicrosporidians & 0 & 5 & 0 & 0\\\\\nMollusks & 14 & 0 & 0 & 0\\\\\nMonocots & 0 & 0 & 23 & 0\\\\\n\\addlinespace\nMosses & 0 & 0 & 1 & 0\\\\\nNematodes & 6 & 0 & 0 & 0\\\\\nPlacozoans & 1 & 0 & 0 & 0\\\\\nPoriferans & 1 & 0 & 0 & 0\\\\\nRed & 0 & 0 & 3 & 0\\\\\n\\addlinespace\nStramenopiles & 0 & 0 & 0 & 8\\\\\nTunicates & 2 & 0 & 0 & 0\\\\\nVertebrates & 331 & 0 & 0 & 0\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n\n\n\n\n## Table of MBBs\n\nIn this example `MBB` is a table with 5149 rows and 4122 columns. It displays, for every MBB, the selected groups (Kingdoms, families, etc.) to which it belongs.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#100\nknitr::kable(MBB[1:20,1:10]) %>%   \n  scroll_box(width = \"100%\", height = \"200px\")\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{lrrrrrrrrr}\n\\toprule\nMBB Id & natural & \\#pathways & Protists & Fungi & Plants & Animals & Alveolates & Amoebozoa & Annelids\\\\\n\\midrule\n0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0.0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0.0.0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0.0.0.0 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n0.0.0.0.0 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n\\addlinespace\n0.0.0.0.0.0 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n0.0.0.1 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n0.0.0.2 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n0.0.1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0.0.1.0 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 1\\\\\n\\addlinespace\n0.0.1.1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0.0.1.1.0 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0.0.1.2 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n0.0.1.3 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n0.0.1.4 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n\\addlinespace\n0.0.1.4.0 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n0.0.1.4.0.0 & 1 & 1 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n0.0.1.5 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0.0.1.6 & 1 & 4 & 3 & 0 & 0 & 1 & 0 & 0 & 0\\\\\n0.0.1.6.0 & 1 & 3 & 0 & 0 & 3 & 0 & 0 & 0 & 0\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n\n\n\n\n## Table of m-DAGs\n\nIn this example `mDAG` is a table with 1132 rows and 5278 columns. It displays, for every m-DAG, the selected groups (Kingdoms, families, etc.) in which it belongs.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(mDAG[1:20,1:10]) %>%   scroll_box(width = \"100%\", height = \"200px\")\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{lrrrrrrrrr}\n\\toprule\nmDAG Id & \\#Categories & Animals & Plants & Fungi & Protists & Alveolates & Amoebozoa & Annelids & Arthropods\\\\\n\\midrule\n0001 & 3 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0002 & 2 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0\\\\\n0003 & 2 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0004 & 3 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0005 & 3 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n\\addlinespace\n0006 & 3 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0007 & 2 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0008 & 3 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0009 & 3 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0010 & 3 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n\\addlinespace\n0011 & 3 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0012 & 3 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0\\\\\n0013 & 3 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0014 & 3 & 0 & 0 & 0 & 1 & 1 & 0 & 0 & 0\\\\\n0015 & 2 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0\\\\\n\\addlinespace\n0016 & 3 & 0 & 0 & 0 & 1 & 0 & 1 & 0 & 0\\\\\n0017 & 3 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0018 & 3 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n0019 & 3 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\\\\n0020 & 3 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(mDAG)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1132 5278\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(mDAG)[1:6]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"mDAG Id\"     \"#Categories\" \"Animals\"     \"Plants\"      \"Fungi\"      \n[6] \"Protists\"   \n```\n\n\n:::\n\n```{.r .cell-code}\nhead(names(mDAG)[7:(dim(mDAG)[2]-1150)])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Alveolates\"        \"Amoebozoa\"         \"Annelids\"         \n[4] \"Arthropods\"        \"Ascomycetes\"       \"Basal angiosperms\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# 28 to 1213  code MBB: 1 if MBB in mDAG 0\n```\n:::\n\n\n\n\n\n\n## Results Table\n\nThe `Results` table contains for every organism (row) the following information: its category (taxonomy), selected group, Full name, m-DAG id and all reactions name id with their corresponding enzyme. When a reaction is present in the corresponding m-DAG, the MBB to which it belongs is displayed in this column.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(Results[1:20,1:10])%>%\n  row_spec(0, angle = 0) %>%   \n  scroll_box(width = \"300%\", height = \"1000px\")\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{llllllrlll}\n\\toprule\n\\rotatebox{0}{Organism} & \\rotatebox{0}{Categories} & \\rotatebox{0}{Groups} & \\rotatebox{0}{mDAG\\_Id} & \\rotatebox{0}{Full\\_Name} & \\rotatebox{0}{R00005(3.5.1.54)} & \\rotatebox{0}{R00009(1.11.1.6)} & \\rotatebox{0}{R00010(3.2.1.28)} & \\rotatebox{0}{R00014(1.2.4.1)} & \\rotatebox{0}{R00014(4.1.1.1)}\\\\\n\\midrule\naaf & Protists\\&\\#124;Stramenopiles\\&\\#124;Pelagophytes & MSA Cluster 3\\&\\#124;MUN Cluster 3 & 0036 & Aureococcus anophagefferens & NA & NA & 0.0.10.0.15 & 0.0.10.0.15 & NA\\\\\naag & Animals\\&\\#124;Arthropods\\&\\#124;Insects & MSA Cluster 2\\&\\#124;MUN Cluster 2 & 0035 & Aedes aegypti (yellow fever mosquito) & NA & 3936 & 0.9.27.7.36.14 & 0.9.27.7.36.14 & NA\\\\\naalb & Animals\\&\\#124;Arthropods\\&\\#124;Insects & MSA Cluster 2\\&\\#124;MUN Cluster 2 & 0276 & Aedes albopictus (Asian tiger mosquito) & NA & 3936 & 0.9.27.7.36.18 & 0.9.27.7.36.18 & NA\\\\\naali & Animals\\&\\#124;Arthropods\\&\\#124;Insects & MSA Cluster 2\\&\\#124;MUN Cluster 2 & 0267 & Anopheles albimanus & NA & 3936 & 0.9.27.7.36.65 & 0.9.27.7.36.65 & NA\\\\\naalt & Fungi\\&\\#124;Ascomycetes\\&\\#124;Dothideomycetes & Fungui and Algae\\&\\#124;MSA Cluster 3\\&\\#124;MSA Fungui and Nematodes and Flatworms\\&\\#124;MUN Cluster 3\\&\\#124;MUN Fungui and Nematodes and Flatworms & 0240 & Alternaria alternata & NA & 3936 & 0.0.9.20.0.5.6.7 & 0.0.9.20.0.5.6.7 & 0.0.9.20.0.5.6.7\\\\\n\\addlinespace\naam & Animals\\&\\#124;Vertebrates\\&\\#124;Birds & Cluster 1 & 0040 & Apteryx mantelli mantelli (North Island brown kiwi) & NA & 3936 & NA & 0.9.26.15.46 & NA\\\\\naamp & Animals\\&\\#124;Vertebrates\\&\\#124;Mammals & Cluster 1 & 0313 & Arvicola amphibius (Eurasian water vole) & NA & 3936 & 0.0.9.20.0.6.0.39 & 0.9.26.18.2.0 & NA\\\\\naang & Animals\\&\\#124;Vertebrates\\&\\#124;Fishes & Cluster 1 & 0317 & Anguilla anguilla (European eel) & NA & 3936 & 0.0.9.20.0.6.0.39 & 0.9.26.17.0.0 & NA\\\\\naara & Animals\\&\\#124;Arthropods\\&\\#124;Insects & MSA Cluster 2\\&\\#124;MUN Cluster 2 & 0362 & Anopheles arabiensis & NA & 3936 & 0.9.27.7.36.34 & 0.9.27.7.36.34 & NA\\\\\nabe & Fungi\\&\\#124;Ascomycetes\\&\\#124;Eurotiomycetes & Fungui and Algae\\&\\#124;MSA Cluster 3\\&\\#124;MSA Fungui and Nematodes and Flatworms\\&\\#124;MUN Cluster 3\\&\\#124;MUN Fungui and Nematodes and Flatworms & 0060 & Trichophyton benhamiae & NA & 3936 & 0.0.9.20.0.5.7.0 & 0.0.9.20.0.5.7.0 & 0.0.9.20.0.5.7.0\\\\\n\\addlinespace\nabp & Fungi\\&\\#124;Basidiomycetes & Fungui and Algae\\&\\#124;MSA Cluster 3\\&\\#124;MSA Fungui and Nematodes and Flatworms\\&\\#124;MUN Cluster 3\\&\\#124;MUN Fungui and Nematodes and Flatworms & 0068 & Agaricus bisporus var. burnettii JB137-S8 & NA & 3936 & 0.0.9.20.0.6.1 & 0.0.9.20.0.6.1 & 0.0.9.20.0.6.1\\\\\nabv & Fungi\\&\\#124;Basidiomycetes & Fungui and Algae\\&\\#124;MSA Cluster 3\\&\\#124;MSA Fungui and Nematodes and Flatworms\\&\\#124;MUN Cluster 3\\&\\#124;MUN Fungui and Nematodes and Flatworms & 0073 & Agaricus bisporus var. bisporus H97 & NA & 3936 & 0.0.9.20.0.6.3 & 0.0.9.20.0.6.3 & 0.0.9.20.0.6.3\\\\\nacan & Protists\\&\\#124;Amoebozoa\\&\\#124;Acanthamoeba & MSA Cluster 3\\&\\#124;MUN Cluster 3 & 0873 & Acanthamoeba castellanii & NA & 3936 & NA & 0.0.10.0.3 & NA\\\\\nacar & Animals\\&\\#124;Vertebrates\\&\\#124;Birds & Cluster 1 & 0884 & Antrostomus carolinensis (chuck-will's-widow) & NA & 3936 & NA & 0.9.26.15.59 & NA\\\\\nacep & Animals\\&\\#124;Arthropods\\&\\#124;Insects & MSA Cluster 2\\&\\#124;MUN Cluster 2 & 0054 & Atta cephalotes (leaf cutting ant) & NA & 3936 & 0.9.27.7.36.56 & 0.9.27.7.36.56 & NA\\\\\n\\addlinespace\nacer & Animals\\&\\#124;Arthropods\\&\\#124;Insects & MSA Cluster 2\\&\\#124;MUN Cluster 2 & 0057 & Apis cerana (Asiatic honeybee) & NA & 3936 & 0.9.27.7.35.34 & 0.9.27.7.35.34 & NA\\\\\nachc & Animals\\&\\#124;Vertebrates\\&\\#124;Birds & Cluster 1 & 0103 & Aquila chrysaetos chrysaetos (golden eagle) & NA & 3936 & NA & 0.9.26.15.2.0 & NA\\\\\nache & Fungi\\&\\#124;Ascomycetes\\&\\#124;Eurotiomycetes & Fungui and Algae\\&\\#124;MSA Cluster 3\\&\\#124;MSA Fungui and Nematodes and Flatworms\\&\\#124;MUN Cluster 3\\&\\#124;MUN Fungui and Nematodes and Flatworms & 0106 & Aspergillus chevalieri & NA & 3936 & 0.0.9.20.0.5.7.2 & 0.0.9.20.0.5.7.2 & 0.0.9.20.0.5.7.2\\\\\nachl & Animals\\&\\#124;Vertebrates\\&\\#124;Birds & Cluster 1 & 0081 & Acanthisitta chloris (rifleman) & NA & 3936 & NA & 0.9.26.15.1.1.0.0 & NA\\\\\nacoz & Animals\\&\\#124;Arthropods\\&\\#124;Insects & MSA Cluster 2\\&\\#124;MUN Cluster 2 & 0255 & Anopheles coluzzii & NA & 3936 & 0.9.27.7.36.22 & 0.9.27.7.36.22 & NA\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(Results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1132 3998\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(Results)[1]# organisms  kegg id  class representant of mDAG\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Organism\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(Results)[2]# taxonomy separate by |\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Categories\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(Results)[3]# groups \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Groups\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(Results)[4]# mDAG_Id \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"mDAG_Id\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(Results)[5]# Full name representant\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Full_Name\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(Results)[6:36]# columns 6 to 3998 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"R00005(3.5.1.54)\"   \"R00009(1.11.1.6)\"   \"R00010(3.2.1.28)\"  \n [4] \"R00014(1.2.4.1)\"    \"R00014(4.1.1.1)\"    \"R00021(1.4.7.1)\"   \n [7] \"R00022(3.2.1.52)\"   \"R00024(4.1.1.39)\"   \"R00028(3.2.1.20)\"  \n[10] \"R00031(1.10.3.1)\"   \"R00032(1.13.11.63)\" \"R00036(4.2.1.24)\"  \n[13] \"R00045(1.10.3.1)\"   \"R00066(2.5.1.9)\"    \"R00068(1.10.3.3)\"  \n[16] \"R00073(1.14.99.1)\"  \"R00075(2.5.1.43)\"   \"R00078(1.16.3.1)\"  \n[19] \"R00084(2.5.1.61)\"   \"R00086(3.6.1.15)\"   \"R00086(3.6.1.5)\"   \n[22] \"R00087(3.6.1.9)\"    \"R00093(1.4.1.14)\"   \"R00095(1.6.5.4)\"   \n[25] \"R00100(1.6.2.2)\"    \"R00102(3.2.2.5)\"    \"R00102(3.2.2.6)\"   \n[28] \"R00103(3.6.1.22)\"   \"R00103(3.6.1.9)\"    \"R00104(2.7.1.23)\"  \n[31] \"R00111(1.14.13.39)\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# reactions name id with its enzyme.\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nreactions=names(Results)[-c(1:5)]\nreverse_reactions=stringr::str_detect(reactions,\"rev\")\nreverse_reactions=table(reverse_reactions)\ndimnames(reverse_reactions)$reverse_reactions=\n  c(\"Non reverse reaction\",\"Reverse reaction\")\nreverse_reactions %>% kable %>%\n  kable_styling(\"striped\", full_width = F,position=\"left\")\n```\n\n::: {.cell-output-display}\n\n\\begin{longtable}[l]{lr}\n\\toprule\nreverse\\_reactions & Freq\\\\\n\\midrule\nNon reverse reaction & 3399\\\\\nReverse reaction & 594\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}