---
title: "Load Data"
output: 
  html_document: 
    toc: yes
    toc_depth: 4
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache=FALSE,
                      warning = FALSE,
                      message = FALSE)
library(tidyverse)
```

## Load data MetaDag experiment


```{r}
experiment="result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf"
path_exp="data/result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf/data/"
dir(path_exp)


```
  
```
experiment="result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf"
path=paste0("data/result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf","/data/")
path
setwd("data/result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf/data/Individuals/")
dir(path)
=paste0("data/result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf","/data/")
path
setwd("data/result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf/data/Individuals/")
dir()
```


```
experiment_id="dc685813-a087-31ac-b0aa-b26d263eca30"
data_raw_path="Experimental_raw_data/result_dc685813-a087-31ac-b0aa-b26d263eca30/data/"
#data_raw_path
dir(data_raw_path,include.dirs = TRUE)
```


```{r}
#"data/result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf/data/"
MBB=read_csv(paste0(path_exp,"Different_MBB.csv"),show_col_types = FALSE)
mDAG=read_csv(paste0(path_exp,"Different_mDAG.csv"),show_col_types = FALSE)
Results=read_csv(paste0(path_exp,"Results.csv"),show_col_types = FALSE)
```

## MBB


En este experimento `MBB`  es una tabla con `r nrow(MBB)` filas y 
`r ncol(MBB)` 2752 columnas.


```{r}
library(knitr)
library(kableExtra)
#add_header_above(c("a" = 5, "b" = 18,"last"=2752-23)) %>%
# kable_paper() %>%
kable(MBB[1:200,1:300]) %>%   scroll_box(width = "100%", height = "200px")
```

Manual columnas MBB

```{r}
#definition_cols=data.frame(col_number,col_name,col,definition)
```




## mDAG


Abstract/unique  mDAG's in  this experiment 

```{r}
dim(mDAG)
```


```{r}
kable(mDAG[1:200,1:300]) %>%   scroll_box(width = "100%", height = "200px")
```



```{r}
dim(mDAG)
names(mDAG)[1:6]
names(mDAG)[7:(dim(mDAG)[2]-1150)]# 28 to 1213  code MBB: 1 if MBB in mDAG 0 
```



## Results


Tabular data  `Results` for this experiment 



```{r}
kable(Results[1:200,1:100])%>%
  row_spec(0, angle = -90) %>%   
  scroll_box(width = "100%", height = "300px")
```



```{r}
dim(Results)
names(Results)[1]# organisms  kegg id  class representant of mDAG
names(Results)[2]# taxonomy separate b y |
names(Results)[3]# mDAG_Id 
names(Results)[4]# Full name representant
names(Results)[6:36]# 6 to 2726  Variable Reactions name id: This reaction belongs to this ball for this MDAG. If not present the value is NA
```




```{r}
library(stringr)
reactions=names(Results)[6:2726]
reverse_reactions=stringr::str_detect(reactions,"rev")
table(reverse_reactions)
```

# Read graph 

```{r}
library(igraph)
gg1_mDAG=read.graph("data/result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf/data/Individuals/hsa/hsa_mDAG.graphml",format = "graphml")
summary(gg1)
barplot(table(degree(gg1)))

#gg1_2=read.graph("Experimental_raw_data/result_dc685813-a087-31ac-b0aa-b26d263eca30/data/Individuals/aag/aag_RC.graphml", format = "graphml")


#gg1_2=read.graph("Experimental_raw_data/result_dc685813-a087-31ac-b0aa-b26d263eca30/data/Individuals/aang/aang_RC.graphml", format = "graphml")


gg1_core_mDAG=read.graph("data/result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf/data/Global/core/core_mDAG.graphml", format = "graphml")

gg1_core_RC=read.graph("data/result_9ed945b7-6fd7-30de-80a3-01b4e8528ebf/data/Global/core/core_RC.graphml", format = "graphml")
```


```{r}
compo=components(gg1_mDAG,mode = "weak")
str(compo)
compo$csize
k=which.max(compo$csize==max(compo$csize))
k
table(compo$membership)
vertex=which(compo$membership==k)
length(vertex)
vertex
V(gg1_mDAG)
CC1=induced_subgraph(gg1_mDAG, vids=vertex)
plot(CC1)
summary(CC1)
```



